// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod testschema {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

pub enum TestOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Test<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Test<'a> {
  type Inner = Test<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Test<'a> {
  pub const VT_VALUE: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Test { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args TestArgs<'args>
  ) -> flatbuffers::WIPOffset<Test<'bldr>> {
    let mut builder = TestBuilder::new(_fbb);
    if let Some(x) = args.value { builder.add_value(x); }
    builder.finish()
  }


  #[inline]
  pub fn value(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Test::VT_VALUE, None)}
  }
}

impl flatbuffers::Verifiable for Test<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("value", Self::VT_VALUE, false)?
     .finish();
    Ok(())
  }
}
pub struct TestArgs<'a> {
    pub value: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for TestArgs<'a> {
  #[inline]
  fn default() -> Self {
    TestArgs {
      value: None,
    }
  }
}

pub struct TestBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> TestBuilder<'a, 'b> {
  #[inline]
  pub fn add_value(&mut self, value: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Test::VT_VALUE, value);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> TestBuilder<'a, 'b> {
    let start = _fbb.start_table();
    TestBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Test<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Test<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Test");
      ds.field("value", &self.value());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Test`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_test_unchecked`.
pub fn root_as_test(buf: &[u8]) -> Result<Test, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<Test>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Test` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_test_unchecked`.
pub fn size_prefixed_root_as_test(buf: &[u8]) -> Result<Test, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<Test>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Test` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_test_unchecked`.
pub fn root_as_test_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Test<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<Test<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Test` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_test_unchecked`.
pub fn size_prefixed_root_as_test_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Test<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<Test<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Test and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Test`.
pub unsafe fn root_as_test_unchecked(buf: &[u8]) -> Test {
  flatbuffers::root_unchecked::<Test>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Test and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Test`.
pub unsafe fn size_prefixed_root_as_test_unchecked(buf: &[u8]) -> Test {
  flatbuffers::size_prefixed_root_unchecked::<Test>(buf)
}
pub const TEST_IDENTIFIER: &str = "TEST";

#[inline]
pub fn test_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, TEST_IDENTIFIER, false)
}

#[inline]
pub fn test_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, TEST_IDENTIFIER, true)
}

#[inline]
pub fn finish_test_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<Test<'a>>) {
  fbb.finish(root, Some(TEST_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_test_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<Test<'a>>) {
  fbb.finish_size_prefixed(root, Some(TEST_IDENTIFIER));
}
}  // pub mod testschema

