job_name = "04_very-simple_demo_60f-1w_eager-naive-coarse"
job_description = "Incredibly simple animation. DEMO. 60 frames, 1 worker, eager naive coarse strategy."

project_file_path = "%BASE%/blender-projects/04_very-simple/04_very-simple.blend"
render_script_path = "%BASE%/scripts/render-timing-script.py"

frame_range_from = 1
frame_range_to = 60

wait_for_number_of_workers = 1

output_directory_path = "%BASE%/blender-projects/04_very-simple/output"
output_file_name_format = "######"
output_file_format = "JPEG"

[frame_distribution_strategy]
strategy_type = "eager-naive-coarse"
target_queue_size = 60
