[package]
name = "serialization"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flatbuffers = "23.1.21"

[build-dependencies]
flatc-rust = "0.2.0"
