job_name = "01_simple-animation_sw-4f"
job_description = "Simple animation (single worker, four frames)."

project_file_path = "%BASE%/blender-projects/01_simple-animation/01_simple-animation.blend"

frame_range_from = 1
frame_range_to = 4

wait_for_number_of_workers = 1

output_directory_path = "%BASE%/blender-projects/01_simple-animation/output"
output_file_name_format = "#####"
output_file_format = "JPEG"

[frame_distribution_strategy]
strategy_type = "naive-fine"
