job_name = "01_simple-animation_f20_nc3"
job_description = "Simple animation (20 frames)."

project_file_path = "%BASE%/blender-projects/01_simple-animation/01_simple-animation.blend"

frame_range_from = 1
frame_range_to = 20

wait_for_number_of_workers = 2

output_directory_path = "%BASE%/blender-projects/01_simple-animation/output"
output_file_name_format = "#####"
output_file_format = "PNG"

[frame_distribution_strategy]
strategy_type = "dynamic"
target_queue_size = 3
min_queue_size_to_steal = 2
min_seconds_before_resteal_to_elsewhere = 15
min_seconds_before_resteal_to_original_worker = 30
