job_name = "01_simple-animation_60f"
job_description = "Simple animation (sixty easy frames)."

project_file_path = "%BASE%/blender-projects/01_simple-animation/01_simple-animation.blend"

frame_range_from = 1
frame_range_to = 60

wait_for_number_of_workers = 2

output_directory_path = "%BASE%/blender-projects/01_simple-animation/output"
output_file_name_format = "#####"
output_file_format = "PNG"
